// <auto-generated />
using System;
using Crumbs.EFCore.ProviderContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Crumbs.EFCore.Migrations.SqliteMigrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20190615183619_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Framework")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Crumbs.EFCore.Models.Event", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AggregateId");

                    b.Property<int>("AggregateVersion");

                    b.Property<Guid>("AppliedByUserId");

                    b.Property<string>("Data")
                        .IsRequired();

                    b.Property<Guid>("SessionId");

                    b.Property<DateTimeOffset>("Timestamp");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("EventId");

                    b.HasIndex("AggregateId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("Crumbs.EFCore.Models.EventHandlerState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data")
                        .IsRequired();

                    b.Property<DateTimeOffset>("LastUpdated");

                    b.Property<long>("ProcessedEventId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("EventHandlerState");
                });

            modelBuilder.Entity("Crumbs.EFCore.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ComittedByUserId");

                    b.Property<DateTimeOffset>("CompletedDate");

                    b.Property<string>("Data")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("Crumbs.EFCore.Models.Snapshot", b =>
                {
                    b.Property<Guid>("AggregateId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<int>("Version");

                    b.HasKey("AggregateId");

                    b.ToTable("Snapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
